

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
- build
- test
- deploy

build:
  stage: build
  script:
    - ./mvnw  dependency:resolve
    - ./mvnw package
  image: eclipse-temurin:17-jre-jammy

test:
  stage: test
  script:
    - ./mvnw  test
  image: eclipse-temurin:17-jre-jammy
deploy:
  stage: deploy
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CERT_PATH: /certs/client
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export IMAGE_TAG=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG  '''