image: docker:18.09
services:
- docker:18.09-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build
- test
- deploy
- package

maven-build:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: build
  script:
  - ./mvnw package > build.log
  - ./mvnw test-compile
  artifacts:
    paths:
    - target/*
    - build.log

maven-test:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: test
  script:
  - ./mvnw test > test.log
  artifacts:
    paths:
    - test.log


deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production



docker_build:
    tags:
    - docker
    image: docker:20.10.16-dind
    stage: package
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

