default:
  tags: [saas-linux-large-amd64] # do not waste your time waiting

stages:
  - build
  - test 
  - config

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true  

build: # task: create variant with AutoBuild! Build through Dockerfile? overwriting the ADO build job which does build and push
  stage: build
  image: maven:3-jdk-8-slim # maven:3-jdk-11-slim
  variables: #the log is too long so I shorten it with following vars
    CI_DEBUG_TRACE: "false"
    JOB_TRACE: "false"
    SECURE_LOG_LEVEL: "false"
    TRACE: "false"
    AUTO_DEVOPS_DEPLOY_DEBUG: "false"
  script:
    - mvn clean install -DskipTests=false # -DskipTests to shorten the build
    - mvn package -DskipTests=false -Dmaven.repo.local=./.m2 # -DskipTests
  cache:
    policy: push
    key: ${CI_COMMIT_SHA}
    paths:
      - .m2
  artifacts:
    paths:
    - "Dockerfile"
    - "target/spring-petclinic-1.5.4.jar"

