image: docker:20.10.16-dind
services:
- docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build
- test
- deploy
- release
- package

maven-build:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: build
  script:
  - ./mvnw package > build.log
  - ./mvnw test-compile
  artifacts:
    paths:
    - target/*
    - build.log

maven-test:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: test
  script:
  - ./mvnw test > test.log
  artifacts:
    paths:
    - test.log


deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.


docker_build:
    tags:
    - docker
    stage: package
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

