image: docker:18.09
services:
- docker:18.09-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build
- test
- release
- package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
  - mvn -Dmaven.test.skip=true package -B > build.log
  - mvn test-compile
  artifacts:
    paths:
    - target/*
    - build.log

maven-test:
  image: maven:3-jdk-8
  stage: test
  script:
  - mvn surefire:test > test.log
  artifacts:
    paths:
    - test.log

release_job:
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job in a tag pipeline
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "Create release"
  release:
    name: 'Petclinic'
    tag_name: '$CI_COMMIT_TAG'


docker-build:
  stage: package
  before_script:
    - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - export WEB_IMAGE=$IMAGE/Petclinic_build
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose-ci.yml build
    - docker tag petclinic_pipe:latest $WEB_IMAGE:latest
    - docker images
    - docker push $WEB_IMAGE:latest


