image: docker:20.10.16-dind



stages:
- build
- test
- package
- release
- deploy


maven-build:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: build
  script:
  - ./mvnw package > build.log
  - ./mvnw test-compile
  artifacts:
    paths:
    - target/*
    - build.log

maven-test:
  tags:
    - docker
  image: eclipse-temurin:17-jdk-jammy
  stage: test
  script:
  - ./mvnw test > test.log
  artifacts:
    paths:
    - test.log

docker_build:
    services:
    - name: docker:20.10.16-dind
      alias: thedockerhost
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
    variables:
      DOCKER_DRIVER: overlay2
      DOCKER_HOST: tcp://thedockerhost:2375/
      DOCKER_TLS_CERTDIR: ""
    tags:
    - docker
    stage: package
    script:
    - apk add --no-cache bash python3
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f dockerfile_multistaging -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest


deploy:
  stage: deploy
  script:
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker run -d -p 5000:8000 $CONTAINER_IMAGE"
  environment: production

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.



